apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/results-svc/k8s?ref=cf78f4584d89a64c85e37abe2d3155166648102f

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: results-config

images:
- name: results-svc
  newName: ghcr.io/flawmop/results-svc
  newTag: cf78f4584d89a64c85e37abe2d3155166648102f

replicas:
- count: 1
  name: results-svc
