apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/results-svc/k8s?ref=aacd24efb4c4353ffa8639870edc4a92e66c45bb

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: results-config

images:
- name: results-svc
  newName: ghcr.io/flawmop/results-svc
  newTag: aacd24efb4c4353ffa8639870edc4a92e66c45bb

replicas:
- count: 1
  name: results-svc
