apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/results-svc/k8s?ref=54e1014fdba3a63e3761440cf6602578c3f4bcf5

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: results-config

images:
- name: results-svc
  newName: ghcr.io/flawmop/results-svc
  newTag: 54e1014fdba3a63e3761440cf6602578c3f4bcf5

replicas:
- count: 1
  name: results-svc
