apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/results-svc/k8s?ref=9f724632a8bbf7db55b8a76877a31edffe57bd63

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: results-config

images:
- name: results-svc
  newName: ghcr.io/flawmop/results-svc
  newTag: 9f724632a8bbf7db55b8a76877a31edffe57bd63

replicas:
- count: 1
  name: results-svc
