apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-svr
spec:
  template:
    spec:
      containers:
        - name: edge-svr
          env:
            - name: KEYCLOAK_ISSUER_URI
              value: http://keycloak.production.insilicosoft.com/realms/Portal
