apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/simulation-invoke-svc/k8s?ref=25bcf9ad6eb4d1ea3871315f7fa6c5706423b984

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: simulation-invoke-config

images:
- name: simulation-invoke-svc
  newName: ghcr.io/flawmop/simulation-invoke-svc
  newTag: 25bcf9ad6eb4d1ea3871315f7fa6c5706423b984

replicas:
- count: 1
  name: simulation-invoke-svc
