apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/simulation-svc/k8s?ref=d4cfdc15082e0f4dcb759bf366224c86fda50245

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: simulation-config

images:
- name: simulation-svc
  newName: ghcr.io/flawmop/simulation-svc
  newTag: d4cfdc15082e0f4dcb759bf366224c86fda50245

replicas:
- count: 1
  name: simulation-svc
