---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-svc
spec:
  template:
    spec:
      containers:
      - name: simulation-svc
        env:
        - name: COM_INSILICOSOFT_EXECUTOR_COREPOOLSIZE
          value: '10'
        - name: COM_INSILICOSOFT_EXECUTOR_MAXPOOLSIZE
          value: '10'
        - name: COM_INSILICOSOFT_EXECUTOR_QUEUECAPACITY
          value: '500'
        - name: COM_INSILICOSOFT_EXECUTOR_THREADNAMEPREFIX
          value: ~Async-prod-
        - name: LOGGING_LEVEL_ROOT
          value: TRACE
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://portal-postgres:5432/portaldb
        - name: SPRING_RABBITMQ_HOST
          value: portal-rabbitmq
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmqpassword
        - name: SPRING_RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmquser
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: http://keycloak.production.insilicosoft.com/realms/Portal
