apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/edge-svr/k8s?ref=2e7c61946609a34b4115edb70ad5da0ed49176bf

patches:
- path: ./patch-env.yml

images:
- name: edge-svr
  newName: ghcr.io/flawmop/edge-svr
  newTag: 2e7c61946609a34b4115edb70ad5da0ed49176bf

replicas:
- count: 1
  name: edge-svr
