apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/edge-svr/k8s?ref=eae747f444dbc5afb92b1263467f2b7da9eb944a

patches:
- path: ./patch-env.yml

images:
- name: edge-svr
  newName: ghcr.io/flawmop/edge-svr
  newTag: eae747f444dbc5afb92b1263467f2b7da9eb944a

replicas:
- count: 1
  name: edge-svr
