apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/edge-svr/k8s?ref=9bfee352bb1c8995fa3d9d05c25aff093e332ead

patches:
- path: ./patch-env.yml

images:
- name: edge-svr
  newName: ghcr.io/flawmop/edge-svr
  newTag: 9bfee352bb1c8995fa3d9d05c25aff093e332ead

replicas:
- count: 1
  name: edge-svr
