apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/edge-svr/k8s?ref=f98e4cf37c00fd36036ac6358c126e8bcea5851e

patches:
- path: ./patch-env.yml

images:
- name: edge-svr
  newName: ghcr.io/flawmop/edge-svr
  newTag: f98e4cf37c00fd36036ac6358c126e8bcea5851e

replicas:
- count: 1
  name: edge-svr
