apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/edge-svr/k8s?ref=35847a9e85ed5eab8457bcfd51983ff4e3d41d7d

patches:
- path: ./patch-env.yml

images:
- name: edge-svr
  newName: ghcr.io/flawmop/edge-svr
  newTag: 35847a9e85ed5eab8457bcfd51983ff4e3d41d7d

replicas:
- count: 1
  name: edge-svr
