apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/edge-svr/k8s?ref=2cd5d5180aa62801bfb95430b848302c13df0378

patches:
- path: ./patch-env.yml

images:
- name: edge-svr
  newName: ghcr.io/flawmop/edge-svr
  newTag: 2cd5d5180aa62801bfb95430b848302c13df0378

replicas:
- count: 1
  name: edge-svr
