apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-svr
spec:
  template:
    spec:
      containers:
        - name: edge-svr
          env:
            - name: KEYCLOAK_URI
              value: https://keycloak.dev.insilicosoft.com/realms/Portal
