apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-svr
spec:
  template:
    spec:
      containers:
        - name: edge-svr
          env:
            - name: KEYCLOAK_ISSUER_URI
              value: https://dev.insilicosoft.com/auth/realms/Portal
            - name: JAVA_TOOL_OPTIONS
              value: -Dlogging.level.root=DEBUG
