apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-svr
spec:
  template:
    spec:
      containers:
        - name: edge-svr
          env:
            - name: KEYCLOAK_ISSUER_URI
              value: https://keycloak.dev.insilicosoft.com/realms/Portal
            - name: JAVA_TOOL_OPTIONS
              value: "-Dlogging.level.root=DEBUG -Djavax.net.ssl.trustStore=/etc/secrets/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit"
          volumeMounts:
            - name: self-signed-certs-volume
              mountPath: /etc/secrets/
              readOnly: true
      volumes:
        - name: self-signed-certs-volume
          secret:
            secretName: self-signed-truststore-jks
            items:
              - key: truststore.jks
                path: truststore.jks

