apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/simulation-invoke-svc/k8s?ref=d98555cbb28f270893a847101d4c4aa05dc5bc73

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: simulation-invoke-config

images:
- name: simulation-invoke-svc
  newName: ghcr.io/flawmop/simulation-invoke-svc
  newTag: d98555cbb28f270893a847101d4c4aa05dc5bc73

replicas:
- count: 1
  name: simulation-invoke-svc
