apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/simulation-invoke-svc/k8s?ref=9e2ac12889fa807f3e9bef43a6015c583c73c232

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: simulation-invoke-config

images:
- name: simulation-invoke-svc
  newName: ghcr.io/flawmop/simulation-invoke-svc
  newTag: 9e2ac12889fa807f3e9bef43a6015c583c73c232

replicas:
- count: 1
  name: simulation-invoke-svc
