apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/simulation-invoke-svc/k8s?ref=f64a4fa3fb53016d76f7b820fe8d0da706a5ef7c

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: simulation-invoke-config

images:
- name: simulation-invoke-svc
  newName: ghcr.io/flawmop/simulation-invoke-svc
  newTag: f64a4fa3fb53016d76f7b820fe8d0da706a5ef7c

replicas:
- count: 1
  name: simulation-invoke-svc
