apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/simulation-invoke-svc/k8s?ref=00d15f1b675794df6246112a7002f52141171400

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: simulation-invoke-config

images:
- name: simulation-invoke-svc
  newName: ghcr.io/flawmop/simulation-invoke-svc
  newTag: 00d15f1b675794df6246112a7002f52141171400

replicas:
- count: 1
  name: simulation-invoke-svc
