apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/simulation-invoke-svc/k8s?ref=a668c55a8538e41efb4fcba7b1d22c0e3206de1f

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: simulation-invoke-config

images:
- name: simulation-invoke-svc
  newName: ghcr.io/flawmop/simulation-invoke-svc
  newTag: a668c55a8538e41efb4fcba7b1d22c0e3206de1f

replicas:
- count: 1
  name: simulation-invoke-svc
