apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/simulation-invoke-svc/k8s?ref=421990cde175e0670f8adf6d2374a032d99e77d8

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: simulation-invoke-config

images:
- name: simulation-invoke-svc
  newName: ghcr.io/flawmop/simulation-invoke-svc
  newTag: 421990cde175e0670f8adf6d2374a032d99e77d8

replicas:
- count: 1
  name: simulation-invoke-svc
