apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-invoke-svc
spec:
  template:
    spec:
      containers:
        - name: simulation-invoke-svc
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dlogging.level.root=DEBUG"
            - name: SPRING_RABBITMQ_HOST
              value: portal-rabbitmq
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqpassword
            - name: SPRING_RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmquser
            - name: URL_APP_MANAGER
              value: http://app-manager:8080/
            - name: URL_RESULTS_SVC
              value: http://results-svc:9004/
