apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/run-input-processing-svc/k8s?ref=b26888efc63ac6754b1242ad2adf99b33b54511e

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: run-input-processing-config

images:
- name: run-input-processing-svc
  newName: ghcr.io/flawmop/run-input-processing-svc
  newTag: b26888efc63ac6754b1242ad2adf99b33b54511e

replicas:
- count: 1
  name: run-input-processing-svc
