apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/submission-svc/k8s?ref=ee4393098378f5d49e83761c955bd6742e7d9b63

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: submission-config

images:
- name: submission-svc
  newName: ghcr.io/flawmop/submission-svc
  newTag: ee4393098378f5d49e83761c955bd6742e7d9b63

replicas:
- count: 1
  name: submission-svc
