apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/submission-svc/k8s?ref=bdf276d7ace4072e3f25e7e8f1adbc09a40fa64c

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: submission-config

images:
- name: submission-svc
  newName: ghcr.io/flawmop/submission-svc
  newTag: bdf276d7ace4072e3f25e7e8f1adbc09a40fa64c

replicas:
- count: 1
  name: submission-svc
