apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/welcome-svc/k8s?ref=835f0bfbca220e925db5125672e3d2f7fb883d7a

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: welcome-config

images:
- name: welcome-svc
  newName: ghcr.io/flawmop/welcome-svc
  newTag: 835f0bfbca220e925db5125672e3d2f7fb883d7a

replicas:
- count: 1
  name: welcome-svc
