apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/welcome-svc/k8s?ref=c762defac47356b09cc94869ff22f6de67a57895

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: welcome-config

images:
- name: welcome-svc
  newName: ghcr.io/flawmop/welcome-svc
  newTag: c762defac47356b09cc94869ff22f6de67a57895

replicas:
- count: 1
  name: welcome-svc
