apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/welcome-svc/k8s?ref=11fc7cf3c28d3f29ad6fc95356bf41e200f1a2b0

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: welcome-config

images:
- name: welcome-svc
  newName: ghcr.io/flawmop/welcome-svc
  newTag: 11fc7cf3c28d3f29ad6fc95356bf41e200f1a2b0

replicas:
- count: 1
  name: welcome-svc
