apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/welcome-svc/k8s?ref=69195eba911fa97e4191bcdd98ae8e95e8dca8eb

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: welcome-config

images:
- name: welcome-svc
  newName: ghcr.io/flawmop/welcome-svc
  newTag: 69195eba911fa97e4191bcdd98ae8e95e8dca8eb

replicas:
- count: 1
  name: welcome-svc
