apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/welcome-svc/k8s?ref=6365987f09540f57251b68a8c7797d756a85429c

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: welcome-config

images:
- name: welcome-svc
  newName: ghcr.io/flawmop/welcome-svc
  newTag: 6365987f09540f57251b68a8c7797d756a85429c

replicas:
- count: 1
  name: welcome-svc
