apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-svc
spec:
  template:
    spec:
      containers:
        - name: welcome-svc
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dlogging.level.root=DEBUG"
