apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/run-input-processing-svc/k8s?ref=1fe41bce34bdc490f4828b2a9320a16f9cee3d6d

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: run-input-processing-config

images:
- name: run-input-processing-svc
  newName: ghcr.io/flawmop/run-input-processing-svc
  newTag: 1fe41bce34bdc490f4828b2a9320a16f9cee3d6d

replicas:
- count: 1
  name: run-input-processing-svc
