apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/run-input-processing-svc/k8s?ref=b3eaef495a1f17bd584891b0a1d986bf2ce0831e

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: run-input-processing-config

images:
- name: run-input-processing-svc
  newName: ghcr.io/flawmop/run-input-processing-svc
  newTag: b3eaef495a1f17bd584891b0a1d986bf2ce0831e

replicas:
- count: 1
  name: run-input-processing-svc
