apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/flawmop/run-input-processing-svc/k8s?ref=c43f88307b11628fe47f8bc6cad76492ad6671c9

patches:
- path: ./patch-env.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: run-input-processing-config

images:
- name: run-input-processing-svc
  newName: ghcr.io/flawmop/run-input-processing-svc
  newTag: c43f88307b11628fe47f8bc6cad76492ad6671c9

replicas:
- count: 1
  name: run-input-processing-svc
