apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-input-processing-svc
spec:
  template:
    spec:
      containers:
        - name: run-input-processing-svc
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dlogging.level.root=DEBUG"
