apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-input-processing-svc
spec:
  template:
    spec:
      containers:
        - name: run-input-processing-svc
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dlogging.level.root=DEBUG"
            - name: SPRING_RABBITMQ_HOST
              value: portal-rabbitmq
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqpassword
            - name: SPRING_RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmquser

